// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetndq7zZRSx2NNBJ4GoJutesluTBEFhI',
    appId: '1:329931020310:web:659eff329f7808b0e17d37',
    messagingSenderId: '329931020310',
    projectId: 'final-project-challenge',
    authDomain: 'final-project-challenge.firebaseapp.com',
    storageBucket: 'final-project-challenge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5QdKeODMtSHdeNhcrHlxH_41rrbw67B4',
    appId: '1:329931020310:android:76ad31e9383ca03de17d37',
    messagingSenderId: '329931020310',
    projectId: 'final-project-challenge',
    storageBucket: 'final-project-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAYNoBpqyauVv_dGkFvNsKqHta6YnCXU',
    appId: '1:329931020310:ios:cb541cda3b6f18dce17d37',
    messagingSenderId: '329931020310',
    projectId: 'final-project-challenge',
    storageBucket: 'final-project-challenge.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
